[package]
name = "nx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.21", features = ["derive", "cargo", "env", "unicode"] }
peg = "0.8.1"
blake3 = "1.3.1"
